direction: right
*.style.font-size: 16
*.style.stroke-width: 4
(* -> *)[*].style.stroke-width: 8
*.style.fill: transparent
# *.shape: image

"Benvenut* nel mio Giardino Digitale": {
  style.stroke: "#ffffff"
  link: https://rexus752.dev
  icon: https://rexus752.dev/_icons/index.svg
}

"Teoria degli insiemi": {
  style.stroke: "#ff7fff"
  link: https://rexus752.dev/teoria-degli-insiemi
  style.font-color: "#ffff7f"
  icon: https://rexus752.dev/_icons/teoria-degli-insiemi.svg
}

"Programmazione": {
  style.stroke: "#ff7f7f"
  link: https://rexus752.dev/programmazione
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/programmazione.svg
}

"Relazioni tra insiemi": {
  style.stroke: "#ffff7f"
  link: https://rexus752.dev/relazioni-tra-insiemi
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/relazioni-tra-insiemi.svg
}

"Matematica": {
  style.stroke: "#ff7f7f"
  link: https://rexus752.dev/matematica
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/matematica.svg
}

"Musica": {
  style.stroke: "#7f7fff"
  link: https://rexus752.dev/musica
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/musica.svg
}

"Algebra lineare": {
  link: https://rexus752.dev/matematica/algebra/algebra-lineare/algebra-lineare
  style.font-color: "#ff7f7f"
}

"Logica matematica": {
  style.stroke: "#7fffff"
  link: https://rexus752.dev/logica-matematica
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/logica-matematica.svg
}

"Torino": {
  style.stroke: "#7f7fff"
  link: https://rexus752.dev/torino
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/torino.svg
}

"Paradigmi di programmazione": {
  style.stroke: "#7f7fff"
  link: https://rexus752.dev/paradigmi-di-programmazione
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/paradigmi-di-programmazione.svg
}

"Politecnico di Torino": {
  style.stroke: "#7f7fff"
  link: https://rexus752.dev/politecnico-di-torino
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/politecnico-di-torino.svg
}

"Università di Torino": {
  style.stroke: "#ff7f7f"
  link: https://rexus752.dev/università-di-torino
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/università-di-torino.svg
}

"Teoremi e dimostrazioni": {
  style.stroke: "#ff7f7f"
  link: https://rexus752.dev/teoremi-e-dimostrazioni
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/teoremi-e-dimostrazioni.svg
}

"Teoria musicale": {
  style.stroke: "#7fffff"
  link: https://rexus752.dev/teoria-musicale
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/teoria-musicale.svg
}

"Informatica": {
  style.stroke: "#ffff7f"
  link: https://rexus752.dev/informatica
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/informatica.svg
}

"Algebra": {
  style.stroke: "#7fff7f"
  link: https://rexus752.dev/matematica/algebra/algebra
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/algebra.svg
}

"Informatica a UniTo": {
  style.stroke: "#ff7f7f"
  link: https://rexus752.dev/informatica-a-unito
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/informatica-a-unito.svg
}

"PoliTeK": {
  style.stroke: "#ffffff"
  link: https://rexus752.dev/politek
  style.font-color: "#ffff7f"
  icon: https://rexus752.dev/_icons/politek.svg
}

"Scienza": {
  style.stroke: "#7fff7f"
  link: https://rexus752.dev/scienza
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/scienza.svg
}

"Paradigma dichiarativo": {
  link: https://rexus752.dev/paradigma-dichiarativo
  style.font-color: "#ff7f7f"
}

"Strutture algebriche": {
  link: https://rexus752.dev/strutture-algebriche
  style.font-color: "#ff7f7f"
}

"Numeri complessi": {
  link: https://rexus752.dev/matematica/algebra/numeri-complessi
  style.font-color: "#ff7f7f"
}

"Funzioni": {
  style.stroke: "#7f7fff"
  link: https://rexus752.dev/matematica/teoria-degli-insiemi/funzioni/funzioni
  style.font-color: "#ffff7f"
  icon: https://rexus752.dev/_icons/funzioni.svg
}

"Variazioni e quoziente di Newton": {
  style.stroke: "#ffffff"
  link: https://rexus752.dev/variazioni-e-quoziente-di-newton
  style.font-color: "#ffffff"
  icon: https://rexus752.dev/_icons/variazioni-e-quoziente-di-newton.svg
}

"Lambda-calcolo": {
  style.stroke: "#ff7f7f"
  link: https://rexus752.dev/lambda-calcolo
  style.font-color: "#ffff7f"
  icon: https://rexus752.dev/_icons/lambda-calcolo.svg
}

"Analisi matematica": {
  style.stroke: "#ffff7f"
  link: https://rexus752.dev/analisi-matematica
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/analisi-matematica.svg
}

"Codifica di Church": {
  style.stroke: "#ffff7f"
  link: https://rexus752.dev/codifica-di-church
  style.font-color: "#ffff7f"
  icon: https://rexus752.dev/_icons/codifica-di-church.svg
}

"Haskell": {
  style.stroke: "#ff7fff"
  link: https://rexus752.dev/haskell
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/haskell.svg
}

"Topologia dei reali": {
  style.stroke: "#7fff7f"
  link: https://rexus752.dev/topologia-dei-reali
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/topologia-dei-reali.svg
}

"Proprietà delle funzioni": {
  style.stroke: "#ffbf7f"
  link: https://rexus752.dev/proprietà-delle-funzioni
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/proprietà-delle-funzioni.svg
}

"Sintassi di base di Haskell": {
  link: https://rexus752.dev/sintassi-di-base-di-haskell
  style.font-color: "#ff7f7f"
}

"Lambda-calcolo semplicemente tipizzato (STLC)": {
  style.stroke: "#7fff7f"
  link: https://rexus752.dev/lambda-calcolo-semplicemente-tipizzato-(stlc)
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/lambda-calcolo-semplicemente-tipizzato-(stlc).svg
}

"Limiti": {
  style.stroke: "#7fffff"
  link: https://rexus752.dev/limiti
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/limiti.svg
}

"Invertibilità di funzioni": {
  link: https://rexus752.dev/invertibilità-di-funzioni
  style.font-color: "#ff7f7f"
}

"Asintoti verticali e orizzontali": {
  style.stroke: "#ff7fff"
  link: https://rexus752.dev/asintoti-verticali-e-orizzontali
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/asintoti-verticali-e-orizzontali.svg
}

"Composizione di funzioni": {
  link: https://rexus752.dev/composizione-di-funzioni
  style.font-color: "#ffff7f"
}

"Funzioni continue": {
  style.stroke: "#7f7fff"
  link: https://rexus752.dev/funzioni-continue
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/funzioni-continue.svg
}

"Tipizzazione in Haskell": {
  link: https://rexus752.dev/tipizzazione-in-haskell
  style.font-color: "#ff7f7f"
}

"Funzioni elementari": {
  style.stroke: "#ff7f7f"
  link: https://rexus752.dev/funzioni-elementari
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/funzioni-elementari.svg
}

"Funzioni in Haskell": {
  link: https://rexus752.dev/funzioni-in-haskell
  style.font-color: "#ff7f7f"
}

"Algoritmo di inferenza": {
  style.stroke: "#7f7fff"
  link: https://rexus752.dev/algoritmo-di-inferenza
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/algoritmo-di-inferenza.svg
}

"Limiti delle funzioni composte": {
  style.stroke: "#ffff7f"
  link: https://rexus752.dev/limiti-delle-funzioni-composte
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/limiti-delle-funzioni-composte.svg
}

"Limiti delle funzioni elementari": {
  style.stroke: "#7fcfff"
  link: https://rexus752.dev/limiti-delle-funzioni-elementari
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/limiti-delle-funzioni-elementari.svg
}

"Proprietà locali delle funzioni continue": {
  style.stroke: "#ffffff"
  link: https://rexus752.dev/proprietà-locali-delle-funzioni-continue
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/proprietà-locali-delle-funzioni-continue.svg
}

"Ricorsione in Haskell": {
  link: https://rexus752.dev/ricorsione-in-haskell
  style.font-color: "#ff7f7f"
}

"Forme indeterminate": {
  style.stroke: "#ff7f7f"
  link: https://rexus752.dev/forme-indeterminate
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/forme-indeterminate.svg
}

"Proprietà globali delle funzioni continue": {
  style.stroke: "#7f7fff"
  link: https://rexus752.dev/proprietà-globali-delle-funzioni-continue
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/proprietà-globali-delle-funzioni-continue.svg
}

"Limiti notevoli": {
  style.stroke: "#7fff7f"
  link: https://rexus752.dev/limiti-notevoli
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/limiti-notevoli.svg
}

"Mia configurazione di NixOS": {
  style.stroke: "#f48780"
  link: https://rexus752.dev/mia-configurazione-di-nixos
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/mia-configurazione-di-nixos.svg
}

"Nix flake": {
  style.stroke: "#b7bb27"
  link: https://rexus752.dev/nix-flake
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/nix-flake.svg
}

"NixOS": {
  style.stroke: "#7ebae4"
  link: https://rexus752.dev/nixos
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/nixos.svg
}

"Configurazione del mio Giardino Digitale": {
  style.stroke: "#7f7fff"
  link: https://rexus752.dev/configurazione-del-mio-giardino-digitale
  style.font-color: "#ffffff"
  icon: https://rexus752.dev/_icons/configurazione-del-mio-giardino-digitale.svg
}

"Nix": {
  style.stroke: "#5277c3"
  link: https://rexus752.dev/nix
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/nixos.svg
}

"Distribuzione del software": {
  style.stroke: "#ffffff"
  link: https://rexus752.dev/distribuzione-del-software
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/distribuzione-del-software.svg
}

"Infiniti e infinitesimi": {
  style.stroke: "#ff7fff"
  link: https://rexus752.dev/infiniti-e-infinitesimi
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/infiniti-e-infinitesimi.svg
}

"Limiti di successioni": {
  link: https://rexus752.dev/limiti-di-successioni
  style.font-color: "#ff7f7f"
}

"Approssimazione locale di funzioni": {
  link: https://rexus752.dev/approssimazione-locale-di-funzioni
  style.font-color: "#ff7f7f"
}

"Primitive": {
  link: https://rexus752.dev/primitive
  style.font-color: "#ff7f7f"
}

"Grafici di derivate": {
  link: https://rexus752.dev/grafici-di-derivate
  style.font-color: "#ff7f7f"
}

"Derivate": {
  link: https://rexus752.dev/derivate
  style.font-color: "#ff7f7f"
}

"Asintoti obliqui": {
  style.stroke: "#7f7fff"
  link: https://rexus752.dev/asintoti-obliqui
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/asintoti-obliqui.svg
}

"Paradigma funzionale": {
  link: https://rexus752.dev/paradigma-funzionale
  style.font-color: "#ff7f7f"
}

"Sistemi operativi": {
  link: https://rexus752.dev/sistemi-operativi
  style.font-color: "#ff7f7f"
}

"Logica per l'informatica": {
  style.stroke: "#7fff7f"
  link: https://rexus752.dev/logica-per-l'informatica
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/logica-per-l'informatica.svg
}

"Sfondi del desktop": {
  style.stroke: "#7fffff"
  link: https://rexus752.dev/sfondi-del-desktop
  style.font-color: "#ffffff"
  icon: https://rexus752.dev/_icons/sfondi-del-desktop.svg
}

"Compilatori": {
  style.stroke: "#ff7fff"
  link: https://rexus752.dev/compilatori
  style.font-color: "#ff7f7f"
  icon: https://rexus752.dev/_icons/compilatori.svg
}

"Teoria dei linguaggi formali": {
  link: https://rexus752.dev/teoria-dei-linguaggi-formali
  style.font-color: "#ff7f7f"
}

"Informatica" -> "Logica per l'informatica": {
  style.stroke: "#ffff7f"
}
"Matematica" -> "Logica matematica": {
  style.stroke: "#ff7f7f"
}
"Informatica" -> "Sfondi del desktop": {
  style.stroke: "#ffff7f"
}
"Teoria degli insiemi" -> "Relazioni tra insiemi": {
  style.stroke: "#ff7fff"
}
"Relazioni tra insiemi" -> "Funzioni": {
  style.stroke: "#ffff7f"
}
"Benvenut* nel mio Giardino Digitale" -> "Torino": {
  style.stroke: "#ffffff"
}
"Torino" -> "Università di Torino": {
  style.stroke: "#7f7fff"
}
"Università di Torino" -> "Informatica a UniTo": {
  style.stroke: "#ff7f7f"
}
"Benvenut* nel mio Giardino Digitale" -> "Musica": {
  style.stroke: "#ffffff"
}
"Musica" -> "Teoria musicale": {
  style.stroke: "#7f7fff"
}
"Torino" -> "Politecnico di Torino": {
  style.stroke: "#7f7fff"
}
"Politecnico di Torino" -> "PoliTeK": {
  style.stroke: "#7f7fff"
}
"Informatica" -> "Lambda-calcolo": {
  style.stroke: "#ffff7f"
}
"Funzioni" -> "Lambda-calcolo": {
  style.stroke: "#7f7fff"
}
"Lambda-calcolo" -> "Codifica di Church": {
  style.stroke: "#ff7f7f"
}
"Codifica di Church" -> "Lambda-calcolo semplicemente tipizzato (STLC)": {
  style.stroke: "#ffff7f"
}
"Lambda-calcolo semplicemente tipizzato (STLC)" -> "Algoritmo di inferenza": {
  style.stroke: "#7fff7f"
}
"Topologia dei reali" -> "Limiti": {
  style.stroke: "#7fff7f"
}
"Funzioni" -> "Analisi matematica": {
  style.stroke: "#7f7fff"
}
"Analisi matematica" -> "Topologia dei reali": {
  style.stroke: "#ffff7f"
}
"Asintoti verticali e orizzontali" -> "Limiti delle funzioni elementari": {
  style.stroke: "#ff7fff"
}
"Funzioni elementari" -> "Limiti delle funzioni elementari": {
  style.stroke: "#ff7f7f"
}
"Asintoti verticali e orizzontali" -> "Proprietà locali delle funzioni continue": {
  style.stroke: "#ff7fff"
}
"Funzioni continue" -> "Limiti delle funzioni composte": {
  style.stroke: "#7f7fff"
}
"Forme indeterminate" -> "Limiti notevoli": {
  style.stroke: "#ff7f7f"
}
"Lambda-calcolo" -> "Haskell": {
  style.stroke: "#ff7f7f"
}
"Limiti" -> "Asintoti verticali e orizzontali": {
  style.stroke: "#7fffff"
}
"Limiti" -> "Funzioni continue": {
  style.stroke: "#7fffff"
}
"Funzioni continue" -> "Proprietà locali delle funzioni continue": {
  style.stroke: "#7f7fff"
}
"Limiti delle funzioni composte" -> "Limiti notevoli": {
  style.stroke: "#ffff7f"
}
"Limiti notevoli" -> "Infiniti e infinitesimi": {
  style.stroke: "#7fff7f"
}
"Infiniti e infinitesimi" -> "Asintoti obliqui": {
  style.stroke: "#ff7fff"
}
"Infiniti e infinitesimi" -> "Limiti di successioni": {
  style.stroke: "#ff7fff"
}
"Proprietà locali delle funzioni continue" -> "Forme indeterminate": {
  style.stroke: "#ffffff"
}
"Proprietà locali delle funzioni continue" -> "Proprietà globali delle funzioni continue": {
  style.stroke: "#ffffff"
}
"Haskell" -> "Sintassi di base di Haskell": {
  style.stroke: "#ff7fff"
}
"Informatica" -> "Programmazione": {
  style.stroke: "#ffff7f"
}
"Paradigma funzionale" -> "Haskell"
"Paradigmi di programmazione" -> "Configurazione del mio Giardino Digitale": {
  style.stroke: "#7f7fff"
}
"Paradigmi di programmazione" -> "Sistemi operativi": {
  style.stroke: "#7f7fff"
}
"Nix" -> "NixOS": {
  style.stroke: "#5277c3"
}
"Teoremi e dimostrazioni" -> "Teoria degli insiemi": {
  style.stroke: "#ff7f7f"
}
"Logica matematica" -> "Teoremi e dimostrazioni": {
  style.stroke: "#7fffff"
}
"Paradigmi di programmazione" -> "Distribuzione del software": {
  style.stroke: "#7f7fff"
}
"Scienza" -> "Informatica": {
  style.stroke: "#7fff7f"
}
"Scienza" -> "Matematica": {
  style.stroke: "#7fff7f"
}
"Benvenut* nel mio Giardino Digitale" -> "Scienza": {
  style.stroke: "#ffffff"
}
"Sistemi operativi" -> "Nix"
"Limiti di successioni" -> "Derivate"
"Derivate" -> "Grafici di derivate"
"Derivate" -> "Primitive"
"Paradigmi di programmazione" -> "Paradigma funzionale": {
  style.stroke: "#7f7fff"
}
"Paradigma funzionale" -> "Nix"
"Distribuzione del software" -> "Nix": {
  style.stroke: "#ffffff"
}
"Paradigmi di programmazione" -> "Paradigma dichiarativo": {
  style.stroke: "#7f7fff"
}
"Paradigma dichiarativo" -> "Nix"
"Variazioni e quoziente di Newton" -> "Proprietà delle funzioni": {
  style.stroke: "#ffffff"
}
"Proprietà delle funzioni" -> "Derivate": {
  style.stroke: "#ffbf7f"
}
"Proprietà delle funzioni" -> "Composizione di funzioni": {
  style.stroke: "#ffbf7f"
}
"Composizione di funzioni" -> "Limiti delle funzioni composte"
"Proprietà delle funzioni" -> "Invertibilità di funzioni": {
  style.stroke: "#ffbf7f"
}
"Invertibilità di funzioni" -> "Funzioni elementari"
"Funzioni continue" -> "Limiti delle funzioni elementari": {
  style.stroke: "#7f7fff"
}
"Derivate" -> "Approssimazione locale di funzioni"
"Logica matematica" -> "Algebra": {
  style.stroke: "#7fffff"
}
"Algebra" -> "Algebra lineare": {
  style.stroke: "#7fff7f"
}
"Funzioni" -> "Variazioni e quoziente di Newton": {
  style.stroke: "#7f7fff"
}
"Strutture algebriche" -> "Numeri complessi"
"Algebra" -> "Strutture algebriche": {
  style.stroke: "#7fff7f"
}
"Relazioni tra insiemi" -> "Strutture algebriche": {
  style.stroke: "#ffff7f"
}
"Sintassi di base di Haskell" -> "Tipizzazione in Haskell"
"Tipizzazione in Haskell" -> "Funzioni in Haskell"
"Funzioni in Haskell" -> "Ricorsione in Haskell"
"Nix" -> "Nix flake": {
  style.stroke: "#5277c3"
}
"NixOS" -> "Mia configurazione di NixOS": {
  style.stroke: "#7ebae4"
}
"Nix flake" -> "Mia configurazione di NixOS": {
  style.stroke: "#b7bb27"
}
"Programmazione" -> "Compilatori": {
  style.stroke: "#ff7f7f"
}
"Programmazione" -> "Paradigmi di programmazione": {
  style.stroke: "#ff7f7f"
}
"Teoria degli insiemi" -> "Teoria dei linguaggi formali": {
  style.stroke: "#ff7fff"
}
