direction: right

"Configurazione del mio Giardino Digitale": {
  link: https://rexus752.github.io/digital-garden/Configurazione-del-mio-Giardino-Digitale
  icon: https://rexus752.github.io/digital-garden/icons/Configurazione-del-mio-Giardino-Digitale.svg
}

"Benvenut* nel mio Giardino Digitale": {
  link: https://rexus752.github.io/digital-garden
  icon: https://rexus752.github.io/digital-garden/icons/Benvenut* nel mio Giardino Digitale.svg
}
"Benvenut* nel mio Giardino Digitale" -> "Appunti"

"Appunti": {
  link: https://rexus752.github.io/digital-garden/Appunti
  icon: https://rexus752.github.io/digital-garden/icons/Appunti.svg
}
"Appunti" -> "Configurazione del mio Giardino Digitale"
"Appunti" -> "Teoria degli insiemi"

"Teoria degli insiemi": {
  link: https://rexus752.github.io/digital-garden/Teoria-degli-insiemi
  icon: https://rexus752.github.io/digital-garden/icons/Teoria-degli-insiemi.svg
}

