direction: right

"Limiti di successioni": {
  link: https://rexus752.dev/limiti-di-successioni
}

"Asintoti obliqui": {
  link: https://rexus752.dev/asintoti-obliqui
  icon: https://rexus752.dev/_icons/asintoti-obliqui.svg
}

"Derivate": {
  link: https://rexus752.dev/derivate
}

"Primitive": {
  link: https://rexus752.dev/primitive
}

"Grafici di derivate": {
  link: https://rexus752.dev/grafici-di-derivate
}

"Approssimazione locale di funzioni": {
  link: https://rexus752.dev/approssimazione-locale-di-funzioni
}

"Benvenut* nel mio Giardino Digitale": {
  link: https://rexus752.dev
  icon: https://rexus752.dev/_icons/index.svg
}

"Torino": {
  link: https://rexus752.dev/torino
  icon: https://rexus752.dev/_icons/torino.svg
}

"Forme indeterminate": {
  link: https://rexus752.dev/forme-indeterminate
  icon: https://rexus752.dev/_icons/forme-indeterminate.svg
}

"Proprietà globali delle funzioni continue": {
  link: https://rexus752.dev/proprietà-globali-delle-funzioni-continue
}

"Limiti notevoli": {
  link: https://rexus752.dev/limiti-notevoli
  icon: https://rexus752.dev/_icons/limiti-notevoli.svg
}

"Infiniti e infinitesimi": {
  link: https://rexus752.dev/infiniti-e-infinitesimi
  icon: https://rexus752.dev/_icons/infiniti-e-infinitesimi.svg
}

"Limiti delle funzioni composte": {
  link: https://rexus752.dev/limiti-delle-funzioni-composte
  icon: https://rexus752.dev/_icons/limiti-delle-funzioni-composte.svg
}

"Funzioni elementari": {
  link: https://rexus752.dev/funzioni-elementari
  icon: https://rexus752.dev/_icons/funzioni-elementari.svg
}

"Limiti delle funzioni elementari": {
  link: https://rexus752.dev/limiti-delle-funzioni-elementari
  icon: https://rexus752.dev/_icons/limiti-delle-funzioni-elementari.svg
}

"Proprietà locali delle funzioni continue": {
  link: https://rexus752.dev/proprietà-locali-delle-funzioni-continue
  icon: https://rexus752.dev/_icons/proprietà-locali-delle-funzioni-continue.svg
}

"Asintoti verticali e orizzontali": {
  link: https://rexus752.dev/asintoti-verticali-e-orizzontali
  icon: https://rexus752.dev/_icons/asintoti-verticali-e-orizzontali.svg
}

"Limiti": {
  link: https://rexus752.dev/limiti
  icon: https://rexus752.dev/_icons/limiti.svg
}

"Funzioni continue": {
  link: https://rexus752.dev/funzioni-continue
  icon: https://rexus752.dev/_icons/funzioni-continue.svg
}

"Algoritmo di inferenza": {
  link: https://rexus752.dev/algoritmo-di-inferenza
  icon: https://rexus752.dev/_icons/algoritmo-di-inferenza.svg
}

"Invertibilità di funzioni": {
  link: https://rexus752.dev/invertibilità-di-funzioni
}

"Proprietà delle funzioni": {
  link: https://rexus752.dev/proprietà-delle-funzioni
}

"Sintassi di base di Haskell": {
  link: https://rexus752.dev/sintassi-di-base-di-haskell
}

"Lambda-calcolo semplicemente tipizzato (STLC)": {
  link: https://rexus752.dev/lambda-calcolo-semplicemente-tipizzato-(stlc)
  icon: https://rexus752.dev/_icons/lambda-calcolo-semplicemente-tipizzato-(stlc).svg
}

"Tipizzazione in Haskell": {
  link: https://rexus752.dev/tipizzazione-in-haskell
}

"Funzioni in Haskell": {
  link: https://rexus752.dev/funzioni-in-haskell
}

"Composizione di funzioni": {
  link: https://rexus752.dev/composizione-di-funzioni
}

"Ricorsione in Haskell": {
  link: https://rexus752.dev/ricorsione-in-haskell
}

"Codifica di Church": {
  link: https://rexus752.dev/codifica-di-church
  icon: https://rexus752.dev/_icons/codifica-di-church.svg
}

"Mia configurazione di NixOS": {
  link: https://rexus752.dev/mia-configurazione-di-nixos
}

"Topologia dei reali": {
  link: https://rexus752.dev/topologia-dei-reali
  icon: https://rexus752.dev/_icons/topologia-dei-reali.svg
}

"Haskell": {
  link: https://rexus752.dev/haskell
  icon: https://rexus752.dev/_icons/haskell.svg
}

"Analisi matematica": {
  link: https://rexus752.dev/analisi-matematica
  icon: https://rexus752.dev/_icons/analisi-matematica.svg
}

"Lambda-calcolo": {
  link: https://rexus752.dev/lambda-calcolo
  icon: https://rexus752.dev/_icons/lambda-calcolo.svg
}

"Variazioni e quoziente di Newton": {
  link: https://rexus752.dev/variazioni-e-quoziente-di-newton
}

"Numeri complessi": {
  link: https://rexus752.dev/matematica/algebra/numeri-complessi
}

"Funzioni": {
  link: https://rexus752.dev/matematica/teoria-degli-insiemi/funzioni/funzioni
  icon: https://rexus752.dev/_icons/funzioni.svg
}

"Paradigma dichiarativo": {
  link: https://rexus752.dev/paradigma-dichiarativo
}

"Strutture algebriche": {
  link: https://rexus752.dev/strutture-algebriche
}

"Nix flake": {
  link: https://rexus752.dev/nix-flake
}

"Sistemi operativi": {
  link: https://rexus752.dev/sistemi-operativi
}

"Nix": {
  link: https://rexus752.dev/nix
  icon: https://rexus752.dev/_icons/nixos.svg
}

"NixOS": {
  link: https://rexus752.dev/nixos
}

"Distribuzione del software": {
  link: https://rexus752.dev/distribuzione-del-software
}

"Paradigma funzionale": {
  link: https://rexus752.dev/paradigma-funzionale
}

"Relazioni tra insiemi": {
  link: https://rexus752.dev/relazioni-tra-insiemi
  icon: https://rexus752.dev/_icons/relazioni-tra-insiemi.svg
}

"Paradigmi di programmazione": {
  link: https://rexus752.dev/paradigmi-di-programmazione
}

"Logica per l'informatica": {
  link: https://rexus752.dev/logica-per-l'informatica
  icon: https://rexus752.dev/_icons/logica-per-l'informatica.svg
}

"Configurazione del mio Giardino Digitale": {
  link: https://rexus752.dev/configurazione-del-mio-giardino-digitale
  icon: https://rexus752.dev/_icons/configurazione-del-mio-giardino-digitale.svg
}

"Sfondi del desktop": {
  link: https://rexus752.dev/sfondi-del-desktop
  icon: https://rexus752.dev/_icons/sfondi-del-desktop.svg
}

"PoliTeK": {
  link: https://rexus752.dev/politek
  icon: https://rexus752.dev/_icons/politek.svg
}

"Politecnico di Torino": {
  link: https://rexus752.dev/politecnico-di-torino
  icon: https://rexus752.dev/_icons/politecnico-di-torino.svg
}

"Algebra": {
  link: https://rexus752.dev/matematica/algebra/algebra
}

"Informatica": {
  link: https://rexus752.dev/informatica
  icon: https://rexus752.dev/_icons/informatica.svg
}

"Logica matematica": {
  link: https://rexus752.dev/logica-matematica
  icon: https://rexus752.dev/_icons/logica-matematica.svg
}

"Matematica": {
  link: https://rexus752.dev/matematica
  icon: https://rexus752.dev/_icons/matematica.svg
}

"Teoria degli insiemi": {
  link: https://rexus752.dev/teoria-degli-insiemi
  icon: https://rexus752.dev/_icons/teoria-degli-insiemi.svg
}

"Programmazione": {
  link: https://rexus752.dev/programmazione
}

"Algebra lineare": {
  link: https://rexus752.dev/matematica/algebra/algebra-lineare/algebra-lineare
}

"Teoremi e dimostrazioni": {
  link: https://rexus752.dev/teoremi-e-dimostrazioni
}

"Informatica a UniTo": {
  link: https://rexus752.dev/informatica-a-unito
  icon: https://rexus752.dev/_icons/informatica-a-unito.svg
}

"Musica": {
  link: https://rexus752.dev/musica
  icon: https://rexus752.dev/_icons/musica.svg
}

"Scienza": {
  link: https://rexus752.dev/scienza
}

"Teoria musicale": {
  link: https://rexus752.dev/teoria-musicale
  icon: https://rexus752.dev/_icons/teoria-musicale.svg
}

"Università di Torino": {
  link: https://rexus752.dev/università-di-torino
  icon: https://rexus752.dev/_icons/università-di-torino.svg
}

"Paradigmi di programmazione" -> "Sistemi operativi"
"NixOS" -> "Mia configurazione di NixOS"
"Paradigmi di programmazione" -> "Distribuzione del software"
"Limiti di successioni" -> "Derivate"
"Derivate" -> "Grafici di derivate"
"Derivate" -> "Primitive"
"Programmazione" -> "Paradigmi di programmazione"
"Paradigmi di programmazione" -> "Paradigma funzionale"
"Nix flake" -> "Mia configurazione di NixOS"
"Paradigmi di programmazione" -> "Paradigma dichiarativo"
"Variazioni e quoziente di Newton" -> "Proprietà delle funzioni"
"Proprietà delle funzioni" -> "Derivate"
"Proprietà delle funzioni" -> "Composizione di funzioni"
"Proprietà delle funzioni" -> "Invertibilità di funzioni"
"Derivate" -> "Approssimazione locale di funzioni"
"Algebra" -> "Algebra lineare"
"Strutture algebriche" -> "Numeri complessi"
"Algebra" -> "Strutture algebriche"
"Sintassi di base di Haskell" -> "Tipizzazione in Haskell"
"Tipizzazione in Haskell" -> "Funzioni in Haskell"
"Funzioni in Haskell" -> "Ricorsione in Haskell"
