term: |latex
  @ \colon \tau_2
|
term.shape: oval

term -> m

m: |latex
  \text{Tree}[M] \colon \tau_1 \to \tau_2
|

term -> n

n: |latex
  \text{Tree}[N] \colon \sigma
|

Vincoli: {
  a: |latex
    \begin{array}{}
      \tau_1 = \sigma
    \end{array}
  |
}
